### PR TITLE
Decrypt bucket name in storj_bridge_get_bucket()

### PR DESCRIPTION
**Pull request by kaloyan-raev**
This is necessary to implement https://github.com/kaloyan-raev/hello-storj/issues/28

### CODE REVIEW

**Comment by kaloyan-raev** [comment]
@braydonf This PR introduces some duplicated code. Should I refactor it to util functions as part of this PR? 

Does it make sense to add a `get-bucket` CLI command?

**Comment by braydonf** [comment]
Must have forget about decrypting the name in this call. I don't think it's necessary to add to the CLI.

**Comment by braydonf** [comment]
Also may not be necessary to refactor (would need to look more at it). Does look like a test isn't passing in CI though.

**Comment by kaloyan-raev** [comment]
I don't think the failing test is related to this PR. If I checkout master and run `make distcheck`, I get the same test failing.

**Comment by kaloyan-raev** [comment]
So this PR caused a regression in the file upload. After fixing it, the tests pass successfully.

**Comment by braydonf** [comment]
Okay, taking a look at this now.
- Look like it's not handling the case that there isn't a bucket found
- There is a missing test for this method

**Comment by braydonf** [comment]
In the goal of moving this along, went ahead and added a test in https://github.com/Storj/libstorj/pull/394

**Pull request merged**
