### PR TITLE
Add function to set username password and key via the command line call

### PR DESCRIPTION
**Pull request by jensamberg**
Add function to set username password and key via the command line call.
I think this is an improved usability.

Also #435 is partial solved. After that I will work on the mnemonic stuff

### CODE REVIEW

**Comment by jtolds** [comment]
Hey Jen! I don't know if you've seen our blog posts or town hall meetings, but it occurs to me in our scramble we haven't done a good job of keeping these repos up to date, so I just updated our README in this repo to reflect the current situation.

Thank you so much for your work, but before you continue more I should inform you development on this repository is on pause until we complete the majority of our new v3 rearchitecture. Most new development is happening in https://github.com/storj/storj

**Comment by jensamberg** [comment]
Hi,

so you are not planning to make v3 C lib?

**Comment by jtolds** [comment]
We are! But it will largely be bindings to our Go library.

**Comment by jensamberg** [comment]
Ok then you can reject the pull request or merge.
I will investigate the Go lib but go further with this lib for my Qt Storj Gui project

**Comment by RichardLitt** [comment]
Hope you had good fortune what that, @jensamberg! 

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this PR for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!

**Pull request closed without merging**
