### PR TITLE
fixes ruby-libstorj #2; related to libstorj #381

### PR DESCRIPTION
**Pull request by bryanchriswhite**
I'm not sure if this fully addresses #381 but it (combined with some ruby) definitely fixes [ruby-libstorj's #2](https://github.com/Storj/ruby-libstorj/issues/2)

### CODE REVIEW

**Comment by braydonf** [comment]
The loop created in `storj_init_env` at https://github.com/bryanchriswhite/libstorj/blob/7b3fc832f35882831ce29855fec5bbedd335861a/src/storj.c#L480-L486 will be not be freed. We should probably either set the loop to `uv_default_loop()` or have an option to pass the loop in with storj_init_env.

**Comment by bryanchriswhite** [comment]
@braydonf like that?

**Comment by bryanchriswhite** [comment]
I hate to be cliche but tests are passing on my machine... What gives?

**Comment by bryanchriswhite** [comment]
nvm... forgot to `make` before running tests ...facepalm

**Comment by braydonf** [comment]
Tested with [node-libstorj] and it works using `uv_default_loop`. I think the is just an extra free at `free(env->loop);` works fine without...

**Comment by braydonf** [comment]
Merged in https://github.com/Storj/libstorj/commit/bf25e2df84a7269472efc0d703000b7207b7fc50

**Comment by bryanchriswhite** [comment]
sweet... thanks :D :+1:

**Pull request merged**
