### PR TITLE
Windows 64bit shared library build

### PR DESCRIPTION
**Pull request by mstuehlinger**
Added support to build libstorj as shared library (dll) for windows and link the cli against it.
Build instructions are included in the Readme.

Existing builds should not be affected. ARM and MacOS couldn't be tested due to a lack of hardware.

### CODE REVIEW

**Comment by TopperDEL** [comment]
Will that DLL be supported by UWP, too?

**Comment by mstuehlinger** [comment]
@TopperDEL It is a c library compiled with the MinGW toolchain. If the UWP allows calls to native dlls it should support it.

**Comment by braydonf** [comment]
Tested compiling it all, and produced DLL and runs with Wine.

**Comment by braydonf** [comment]
FYI, another iteration on this would be to have depend build as static with `--with-pic`. I have this working for `.so` on linux at https://github.com/Storj/libstorj/pull/359

**Pull request merged**
